Fix bin/setup on some systems
* Some versions of bash return relative paths for `which`
* Others return absolute paths
* Use an approach which doesn't care

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -55,11 +55,14 @@ install_dependencies() {
 }
 
 check_sandbox_path() {
-  if [ "$(which yesod)" != "./.cabal-sandbox/bin/yesod" ]; then
-    printf "Error: couldn't find sandboxed yesod from PATH\n" >&2
-    printf "Add ./.cabal-sandbox/bin to your PATH and run ./bin/setup again\n" >&2
-    exit 1
-  fi
+  case "$(which yesod)" in
+    *cabal-sandbox*) : ;;
+    *)
+      printf "Error: couldn't find sandboxed yesod from PATH\n" >&2
+      printf "Add ./.cabal-sandbox/bin to your PATH and run ./bin/setup again\n" >&2
+      exit 1
+      ;;
+  esac
 }
 
 test_connection() {
